package com.opencaresens.air.model;

/**
 * Persistent algorithm state — massive struct holding all inter-reading state (117312 bytes in C).
 * Maps to air1_opcal4_arguments_t.
 */
public class AlgorithmState {
    public int argsSeq;
    public int lotType;
    public long sensorStartTime;
    public int idxOriginSeq;
    public long timePrev;
    public int seqPrev;
    public int[] adcPrev;
    public double tempPrev;
    public int cumulSum;
    public long[] time10secArr;
    public int contactErrStartSeq;
    public int prevContactErrAlgoSeq;
    public long[] timeStandardArr;
    public int idx;
    public int[] accuSeq;
    public double[] prevCurrent;
    public double[] prevNewISig;
    public int[] outlierMaxIndex;
    public double[] prevOutlierRemovedCurr;
    public double[] prevMovMedianCurr;
    public double[] currAvgArr;
    public int diabetesCntHiGlu;
    public int diabetesCntLowGlu;
    public int diabetesCntIdx;
    public int diabetesLevelDiabetes;
    public double diabetesTAR;
    public double diabetesTBR;
    public double diabetesCV;
    public double diabetesMeanX;
    public double diabetesM2;
    public double shiftoutAdPrev;
    public int diabetesBefore7daysNValid;
    public int diabetesBefore7daysFlag;
    public double diabetesBefore7daysEAG;
    public double diabetesBefore7daysM2;
    public double diabetesBefore7daysTAR;
    public double diabetesBefore7daysTIR;
    public double diabetesBefore7daysCV;
    public double sumCurrForInitValue;
    public int sumCurrCntForInitValue;
    public double sumCurrForMdc;
    public int sumCurrCntForMdc;
    public double[] iirX;
    public double iirY;
    public int iirStartFlag;
    public int mdcStartIdx;
    public int mdcFirstFlag;
    public int iirUseFlag;
    public double baselinePrev;
    public double[] slopeRatioTempBuffer;
    public double[] biastrend;
    public double[] biasIIR;
    public double[] biasavg;
    public double nSumtrend;
    public int biasFlag;
    public int biasCnt;
    // _pad_bias omitted (padding only)
    public double holtLevel;
    public double holtForecast;
    public double holtTrend;
    public double[] kalmanRoc;
    public double kalmanStateFluctuation;
    public double initCgPrev;
    public double[] smoothSigIn;
    public long[] smoothTimeIn;
    public int[] smoothFRepIn;
    public double[] calResultInput;
    public double[] calResultOutput;
    public double[] calResultSlope;
    public double[] calResultYcept;
    public double[] calResultInSmoothSlope;
    public double[] calResultInSmoothYcept;
    public CalibrationLog[] calLog;
    public int calLogCalState;
    public double calLogCslopeDelta;
    public double calLogCyceptDelta;
    public int calState;
    public int stateReturnOpcal;
    public double initstableWeightUsercal;
    public double initstableWeightNocal;
    public double initstableFixusercal;
    public double initstableWeightTempuser;
    public double[] initstableWeightUsercalArr;
    public double[] initstableWeightFaccalArr;
    public double[] initstableMeanDc;
    public double initstableDiffDc;
    public int initstableWeightcontrolOnoff;
    public int initstableBweightstart;
    public int initstableControlCnt;
    public int initstableInitcnt;
    public int initstableFinishInitFlag;
    public int initstableInitEndPoint;
    public int initstableBFirstInit;
    public int startSeq;
    public long cgmTimeStart;
    public int[] errDelayArr;
    public double[] errGluArr;
    public double err1ThSseDMean1;
    public double err1ThSseDMean2;
    public double err1ThSseDMean;
    public double err1ThDiff1;
    public double err1ThDiff2;
    public double err1ThDiff;
    public int err1N;
    public int err1Isfirst0;
    public int err1Isfirst1;
    public int err1Isfirst2;
    public double err1PrevLast1minCurr;
    public int[] err1IsContactBad1h;
    public double[] err1ISseDMean4h;
    public double[] err1CurrentAvgDiffPrev;
    public double[] err1SG1min;
    public long[] err1Time1min;
    public double[] err1InA1min;
    public int err1ResultPrev;
    public int[] err1TDTemporaryBreakFlagPastRange;
    public int err1SumResultConditionTD;
    public int err1AnyResultConditionTD;
    public int err2DelayCondiPrev;
    public int[] err2DelayFlagPrev;
    public double[] err2DelayRocPrev;
    public double[] err2DelaySlopeSharpPrev;
    public double[] err2DelayGlucosevaluePrev;
    public double err2DelayRocCummaxPrev;
    public double err2DelaySlopeCummaxPrev;
    public double err2DelayGluCummaxPrev;
    public int[] err2DelayPreCondiPrev;
    public double err2DelayRevisedValuePrev;
    public double err2Cummax;
    public double[] err2CummaxForetime;
    public int err2ResultPrev;
    public double[] err4InA;
    public double[] err4MinPrev;
    public double[] err4RangePrev;
    public double[] err4MinDiffPrev;
    public int[] err4DelayFlagArr;
    public int err4ResultPrev;
    public int err8ResultPrev;
    public int[] err128FlagPrev;
    public double err128NormalPrev;
    public double err128RevisedValuePrev;
    public double[] err128CgmCNoiseRevisedValue;
    public long err16Time5First;
    public double[] err16DtArr;
    public int err16CalConsIsFirst;
    public double[] err16CalConsSeq;
    public long[] err16CalConsTime;
    public double[] err16CalConsBgm;
    public double[] err16CalConsDUsercalBefore;
    public double[] err16CalConsDUsercalAfter;
    public int err16CalDayI;
    public int err16CalDayIsFirst;
    public int[] err16CalDayIdxRef;
    public double err16CalDayDRef;
    public double err16CalDayDTemp;
    public double[] err16CalDayDValue;
    public double err16CalDayNRef;
    public int[] err16CalDayNValue;
    public double[] err16CgmIsfSmooth;
    public double[] err16CgmPlasma;
    public double err16CgmIsfRocN;
    public double[] err16CgmIsfRocValue;
    public double[] err16CgmIsfRocSteady;
    public double err16CgmIsfRocMin;
    public double[] err16CgmIsfRocMinTemp;
    public double err16CgmIsfRocMinPrev;
    public double[] err16CgmIsfRocDiff;
    public double[] err16CgmIsfRocRatio;
    public double err16CgmIsfTrendMinN;
    public double err16CgmIsfTrendMinValue;
    public double err16CgmIsfTrendMinValuePrev;
    public double[] err16CgmIsfTrendMinValueArr;
    public double[] err16CgmIsfTrendMinSlope1;
    public double[] err16CgmIsfTrendMinSlope2;
    public double[] err16CgmIsfTrendMinRsq1;
    public double[] err16CgmIsfTrendMinRsq2;
    public double[] err16CgmIsfTrendMinDiff;
    public double[] err16CgmIsfTrendMinRatio;
    public double err16CgmIsfTrendMinMax;
    public double[] err16CgmIsfTrendMinMaxTemp;
    public double err16CgmIsfTrendMinMaxPrev;
    public double err16CgmIsfTrendMinMaxEarly;
    public double err16CgmIsfTrendModeN;
    public double err16CgmIsfTrendModeValue;
    public double err16CgmIsfTrendModeValuePrev;
    public double[] err16CgmIsfTrendModeProportion;
    public double[] err16CgmIsfTrendModeDiff;
    public double[] err16CgmIsfTrendModeRatio;
    public double err16CgmIsfTrendModeMax;
    public double[] err16CgmIsfTrendModeMaxTemp;
    public double err16CgmIsfTrendModeMaxPrev;
    public double err16CgmIsfTrendModeMaxEarly;
    public int err16CgmIsfTrendMeanIsFirst;
    public double err16CgmIsfTrendMeanN;
    public double err16CgmIsfTrendMeanValue;
    public double err16CgmIsfTrendMeanValuePrev;
    public double[] err16CgmIsfTrendMeanValueArr;
    public double[] err16CgmIsfTrendMeanSlope;
    public double[] err16CgmIsfTrendMeanRsq;
    public double[] err16CgmIsfTrendMeanDiff;
    public double[] err16CgmIsfTrendMeanRatio;
    public double err16CgmIsfTrendMeanMax;
    public double[] err16CgmIsfTrendMeanMaxTemp;
    public double err16CgmIsfTrendMeanMaxPrev;
    public double err16CgmIsfTrendMeanMaxEarly;
    public double err16CgmIsfTrendMeanMaxEarlyPrev;
    public double[] err16CgmIsfTrendMeanDiffEarly;
    public double[] err16CgmIsfTrendMeanMaxTempEarly;
    public double[] err16CgmIsfTrendMeanRatioEarly;
    public int err16ResultPrev;
    public long err32PrevTime;
    public int err32PrevSeq;
    public int[] err32Buff23;
    public int[] err32Buff60;
    public int err32Buff600;
    public int[] err32N;
    public int err32ResultPrev;

    public AlgorithmState() {
        adcPrev = new int[30];
        time10secArr = new long[90];
        timeStandardArr = new long[288];
        accuSeq = new int[865];
        prevCurrent = new double[5];
        prevNewISig = new double[5];
        outlierMaxIndex = new int[6];
        prevOutlierRemovedCurr = new double[60];
        prevMovMedianCurr = new double[3];
        currAvgArr = new double[865];
        iirX = new double[2];
        slopeRatioTempBuffer = new double[4];
        biastrend = new double[2];
        biasIIR = new double[2];
        biasavg = new double[2];
        kalmanRoc = new double[4];
        smoothSigIn = new double[10];
        smoothTimeIn = new long[10];
        smoothFRepIn = new int[6];
        calResultInput = new double[7];
        calResultOutput = new double[7];
        calResultSlope = new double[7];
        calResultYcept = new double[7];
        calResultInSmoothSlope = new double[10];
        calResultInSmoothYcept = new double[10];
        calLog = new CalibrationLog[50];
        for (int i = 0; i < 50; i++) {
            calLog[i] = new CalibrationLog();
        }
        initstableWeightUsercalArr = new double[7];
        initstableWeightFaccalArr = new double[7];
        initstableMeanDc = new double[2];
        errDelayArr = new int[7];
        errGluArr = new double[288];
        err1IsContactBad1h = new int[100];
        err1ISseDMean4h = new double[100];
        err1CurrentAvgDiffPrev = new double[100];
        err1SG1min = new double[180];
        err1Time1min = new long[180];
        err1InA1min = new double[180];
        err1TDTemporaryBreakFlagPastRange = new int[36];
        err2DelayFlagPrev = new int[575];
        err2DelayRocPrev = new double[575];
        err2DelaySlopeSharpPrev = new double[575];
        err2DelayGlucosevaluePrev = new double[575];
        err2DelayPreCondiPrev = new int[3];
        err2CummaxForetime = new double[100];
        err4InA = new double[390];
        err4MinPrev = new double[289];
        err4RangePrev = new double[51];
        err4MinDiffPrev = new double[289];
        err4DelayFlagArr = new int[576];
        err128FlagPrev = new int[40];
        err128CgmCNoiseRevisedValue = new double[36];
        err16DtArr = new double[36];
        err16CalConsSeq = new double[50];
        err16CalConsTime = new long[50];
        err16CalConsBgm = new double[50];
        err16CalConsDUsercalBefore = new double[50];
        err16CalConsDUsercalAfter = new double[50];
        err16CalDayIdxRef = new int[30];
        err16CalDayDValue = new double[30];
        err16CalDayNValue = new int[30];
        err16CgmIsfSmooth = new double[865];
        err16CgmPlasma = new double[36];
        err16CgmIsfRocValue = new double[577];
        err16CgmIsfRocSteady = new double[36];
        err16CgmIsfRocMinTemp = new double[865];
        err16CgmIsfRocDiff = new double[36];
        err16CgmIsfRocRatio = new double[36];
        err16CgmIsfTrendMinValueArr = new double[865];
        err16CgmIsfTrendMinSlope1 = new double[36];
        err16CgmIsfTrendMinSlope2 = new double[36];
        err16CgmIsfTrendMinRsq1 = new double[36];
        err16CgmIsfTrendMinRsq2 = new double[36];
        err16CgmIsfTrendMinDiff = new double[36];
        err16CgmIsfTrendMinRatio = new double[36];
        err16CgmIsfTrendMinMaxTemp = new double[865];
        err16CgmIsfTrendModeProportion = new double[36];
        err16CgmIsfTrendModeDiff = new double[36];
        err16CgmIsfTrendModeRatio = new double[36];
        err16CgmIsfTrendModeMaxTemp = new double[865];
        err16CgmIsfTrendMeanValueArr = new double[865];
        err16CgmIsfTrendMeanSlope = new double[36];
        err16CgmIsfTrendMeanRsq = new double[36];
        err16CgmIsfTrendMeanDiff = new double[36];
        err16CgmIsfTrendMeanRatio = new double[36];
        err16CgmIsfTrendMeanMaxTemp = new double[865];
        err16CgmIsfTrendMeanDiffEarly = new double[36];
        err16CgmIsfTrendMeanMaxTempEarly = new double[865];
        err16CgmIsfTrendMeanRatioEarly = new double[36];
        err32Buff23 = new int[4];
        err32Buff60 = new int[2];
        err32N = new int[3];
    }
}
