package com.opencaresens.air.model;

/**
 * Debug oracle output — all intermediate values for one reading (1579 bytes packed in C).
 * Maps to air1_opcal4_debug_t.
 */
public class DebugOutput {
    public int seqNumberOriginal;
    public int seqNumberFinal;
    public long measurementTimeStandard;
    public int dataType;
    public int stage;
    public double temperature;
    public int[] workout;
    public double[] tranInA;
    public double[] tranInA1min;
    public double tranInA5min;
    public double ycept;
    public double correctedReCurrent;
    public double diabetesMeanX;
    public double diabetesM2;
    public double diabetesTAR;
    public double diabetesTBR;
    public double diabetesCV;
    public int levelDiabetes;
    public double outIir;
    public double outDrift;
    public double currBaseline;
    public double initstableDiffDc;
    public int initstableInitcnt;
    public double tempLocalMean;
    public double slopeRatioTemp;
    public double initCg;
    public double outRescale;
    public double opcalAd;
    public int stateInitKalman;
    public int[] smoothSeq;
    public double[] smoothSig;
    public int[] smoothFrep;
    public int calState;
    public int stateReturnOpcal;
    public long validBgTime;
    public double validBgValue;
    public int callogGroup;
    public long callogBgTime;
    public double callogBgSeq;
    public double callogBgUser;
    public int callogBgValid;
    public double callogBgCal;
    public double callogCgSeq1m;
    public int callogCgIdx;
    public double callogCgCal;
    public double callogCslopePrev;
    public double callogCyceptPrev;
    public double callogCslopeNew;
    public double callogCyceptNew;
    public int callogInlierFlg;
    public double[] calSlope;
    public double[] calYcept;
    public double[] calInput;
    public double[] calOutput;
    public double initstableWeightUsercal;
    public double initstableWeightNocal;
    public double initstableFixusercal;
    public int nOpcalState;
    public int initstableInitEndPoint;
    public double[] outWeightSd;
    public double outWeightAd;
    public double shiftoutAd;
    public int errorCode1;
    public int errorCode2;
    public int errorCode4;
    public int errorCode8;
    public int errorCode16;
    public int errorCode32;
    public double trendrate;
    public int calAvailableFlag;
    public double err1ISseDMean;
    public double err1ThSseDMean1;
    public double err1ThSseDMean2;
    public double err1ThSseDMean;
    public int err1IsContactBad;
    public double err1CurrentAvgDiff;
    public double err1ThDiff1;
    public double err1ThDiff2;
    public double err1ThDiff;
    public int err1Isfirst0;
    public int err1Isfirst1;
    public int err1Isfirst2;
    public int err1N;
    public int err1RandomNoiseTempBreak;
    public int err1Result;
    public int err1LengthT2Max;
    public int err1LengthT3Max;
    public int err1LengthT1Trio;
    public int err1LengthT2Trio;
    public int err1LengthT3Trio;
    public int err1LengthT6Trio;
    public int err1LengthT7Trio;
    public int err1LengthT8Trio;
    public int err1LengthT9Trio;
    public int err1LengthT10Trio;
    public int err1ResultTD;
    public int[] err1ResultConditionTD;
    public int err1TDCount;
    public int err1TDTemporaryBreakFlag;
    public long[] err1TDTimeTrio;
    public double[] err1TDValueTrio;
    public double err2DelayRevisedValue;
    public double err2DelayRoc;
    public double err2DelaySlopeSharp;
    public double err2DelayRocCummax;
    public double err2DelayRocTrimmedMean;
    public double err2DelaySlopeCummax;
    public double err2DelaySlopeTrimmedMean;
    public double err2DelayGluCummax;
    public double err2DelayGluTrimmedMean;
    public int[] err2DelayPreCondi;
    public int[] err2DelayCondi;
    public int err2DelayFlag;
    public double err2Cummax;
    public int[] err2CrtCurrent;
    public int[] err2CrtGlu;
    public double err2CrtCv;
    public int[] err2Condi;
    public double err4Min;
    public double err4Range;
    public double err4MinDiff;
    public int[] err4Condi;
    public int[] err4DelayCondi;
    public int err4DelayFlag;
    public int[] err8Condi;
    public double err16CalConsDUsercalAfter;
    public double err16CalDayDTemp;
    public double err16CalDayDRef;
    public double err16CalDayNRef;
    public double err16CgmPlasma;
    public double err16CgmIsfSmooth;
    public double err16CgmIsfRocValue;
    public double err16CgmIsfRocSteady;
    public double err16CgmIsfRocMinTemp;
    public double err16CgmIsfRocMin;
    public double err16CgmIsfRocDiff;
    public double err16CgmIsfRocRatio;
    public double err16CgmIsfTrendMinValue;
    public double err16CgmIsfTrendMinSlope1;
    public double err16CgmIsfTrendMinSlope2;
    public double err16CgmIsfTrendMinRsq1;
    public double err16CgmIsfTrendMinRsq2;
    public double err16CgmIsfTrendMinDiff;
    public double err16CgmIsfTrendMinMaxTemp;
    public double err16CgmIsfTrendMinMax;
    public double err16CgmIsfTrendMinRatio;
    public double err16CgmIsfTrendModeValue;
    public double err16CgmIsfTrendModeProportion;
    public double err16CgmIsfTrendModeDiff;
    public double err16CgmIsfTrendModeMaxTemp;
    public double err16CgmIsfTrendModeMax;
    public double err16CgmIsfTrendModeRatio;
    public double err16CgmIsfTrendMeanValue;
    public double err16CgmIsfTrendMeanSlope;
    public double err16CgmIsfTrendMeanRsq;
    public double err16CgmIsfTrendMeanDiff;
    public double err16CgmIsfTrendMeanMaxTemp;
    public double err16CgmIsfTrendMeanMax;
    public double err16CgmIsfTrendMeanRatio;
    public double err16CgmIsfTrendMeanDiffEarly;
    public double err16CgmIsfTrendMeanMaxTempEarly;
    public double err16CgmIsfTrendMeanMaxEarly;
    public double err16CgmIsfTrendMeanRatioEarly;
    public int[] err16Condi;
    public int err128Flag;
    public double err128RevisedValue;
    public double err128Normal;

    public DebugOutput() {
        workout = new int[30];
        tranInA = new double[30];
        tranInA1min = new double[5];
        smoothSeq = new int[6];
        smoothSig = new double[6];
        smoothFrep = new int[6];
        calSlope = new double[7];
        calYcept = new double[7];
        calInput = new double[7];
        calOutput = new double[7];
        outWeightSd = new double[6];
        err1ResultConditionTD = new int[2];
        err1TDTimeTrio = new long[3];
        err1TDValueTrio = new double[3];
        err2DelayPreCondi = new int[3];
        err2DelayCondi = new int[3];
        err2CrtCurrent = new int[2];
        err2CrtGlu = new int[2];
        err2Condi = new int[2];
        err4Condi = new int[5];
        err4DelayCondi = new int[5];
        err8Condi = new int[2];
        err16Condi = new int[7];
    }
}
