package com.opencaresens.air.model;

/**
 * Factory calibration parameters from sensor BLE advertisement (446 bytes packed in C).
 * Maps to air1_opcal4_device_info_t.
 */
public class DeviceInfo {
    public int sensorVersion;
    public float ycept;
    public float slope100;
    public float slope;
    public float r2;
    public float t90;
    public float slopeRatio;
    public String lot;
    public String sensorId;
    public String expiryDate;
    public int stabilizationInterval;
    public int cgmDataInterval;
    public int bleAdvInterval;
    public int bleAdvDuration;
    public int age;
    public int allowedList;
    public float maximumValue;
    public float minimumValue;
    public int cLibraryVersion;
    public int parameterVersion;
    public int basicWarmup;
    public float basicYcept;
    public int contactWinLen;
    public int contactCond1X10;
    public int contactCond2X10;
    public int contactCond3X10;
    public int fillFlag;
    public int driftCorrectionOn;
    public float[][] driftCoefficient;
    public int iRefX100;
    public int coefLength;
    public int divPoint;
    public int iirFlag;
    public int iirStDX10;
    public int correct1Flag;
    public float[] correct1Coeff;
    public int kalmanT90;
    public int kalmanDeltaT;
    public int[][] kalmanQX100;
    public int kalmanRX100;
    public float bgCalRatio;
    public int bgCalTimeFactor;
    public int slopeFactorX10;
    public int slopeInterUpX10;
    public int slopeInterDownX10;
    public int slopeMultiVX10;
    public int slopeIirThr;
    public int slopeNegInterThr1X10;
    public int slopeNegInterThr2X10;
    public int slopeBgCalThrDown;
    public int slopeBgCalThrUp;
    public int slopeMaxSlopeX100;
    public int slopeMinSlopeX100;
    public float slopeDcalRate;
    public int slopeDcalTargetLength;
    public int slopeDcalWindow;
    public int slopeDcalFactoryCalUse;
    public int shiftMSel;
    public float[] shiftCoeff;
    public int[] shiftM2X100;
    public int[] wSgX100;
    public int calTrendRate;
    public float calNoise;
    public int errcodeVersion;
    public int[] err1Seq;
    public float err1ContactBad;
    public float err1ThDiff;
    public float[] err1ThSseDmean;
    public int[] err1ThN1;
    public int[][] err1ThN2;
    public int err1NConsecutive;
    public float[] err1ISseDmeanNow;
    public int err1CountSseDmean;
    public int err1NLast;
    public int[] err1Multi;
    public float err1CurrentAvgDiff;
    public int err2StartSeq;
    public int[] err2Seq;
    public float err2Glu;
    public float[] err2Cv;
    public int err2Cummax;
    public int err2Multi;
    public float err2Ycept;
    public float err2Alpha;
    public int[] err345Seq1;
    public int err345Seq2;
    public int[] err345Seq3;
    public int[] err345Seq4;
    public int[] err345Seq5;
    public float[] err345Raw;
    public float[] err345Filtered;
    public float[] err345Min;
    public float err345Range;
    public int err345NRange;
    public float err345Md;
    public int err345NMd;
    public int err6CalNPts;
    public float err6CalBasicPrct;
    public int err6CalBasicSeq;
    public float err6CalOriginSlope;
    public float[] err6CalInVitro;
    public float err6CgmRpd;
    public float err6CgmSlp;
    public int err6CgmLow3dSeq;
    public float err6CgmLow3dP;
    public int err6CgmLow1dSeq;
    public float err6CgmLow1dP;
    public int[] err6CgmPrct;
    public int[] err6CgmDay;
    public int[] err6CgmBleBad;
    public float err6CgmPoly2;
    public int[] err32Dt;
    public int[] err32N;
    public float vref;
    public float eapp;
    public long sensorStartTime;

    public DeviceInfo() {
        lot = "";
        sensorId = "";
        expiryDate = "";
        driftCoefficient = new float[3][3];
        correct1Coeff = new float[4];
        kalmanQX100 = new int[3][3];
        shiftCoeff = new float[4];
        shiftM2X100 = new int[3];
        wSgX100 = new int[7];
        err1Seq = new int[3];
        err1ThSseDmean = new float[3];
        err1ThN1 = new int[4];
        err1ThN2 = new int[2][2];
        err1ISseDmeanNow = new float[2];
        err1Multi = new int[2];
        err2Seq = new int[3];
        err2Cv = new float[3];
        err345Seq1 = new int[2];
        err345Seq3 = new int[3];
        err345Seq4 = new int[5];
        err345Seq5 = new int[3];
        err345Raw = new float[4];
        err345Filtered = new float[2];
        err345Min = new float[2];
        err6CalInVitro = new float[2];
        err6CgmPrct = new int[3];
        err6CgmDay = new int[2];
        err6CgmBleBad = new int[2];
        err32Dt = new int[2];
        err32N = new int[2];
    }
}
